/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ccTokenSol from "./CCToken.sol";
export type { ccTokenSol };
import type * as christmasClubSol from "./ChristmasClub.sol";
export type { christmasClubSol };
export type { DateTime } from "./DateTime";
